- name: Add DB2 users
  ansible.builtin.include_role:
    name: common
    tasks_from: add-db2-user
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_db2_user: aeos
    common_db2_password: "{{ cp4ba_db2_universal_password }}"

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=engine-creating-database
# Based on https://www.ibm.com/docs/en/filenet-p8-platform/latest?topic=vtdluwiifp-creating-db2-database-table-spaces-content-platform-engine-object-store
- name: AAE Data persistence DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 CONNECT TO CP4BA;
      db2 CREATE LARGE TABLESPACE AEOS_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE USER TEMPORARY TABLESPACE AEOS_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE AEOS_SYSTMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;

      db2 GRANT DBADM ON DATABASE TO user aeos;
      db2 GRANT USE OF TABLESPACE AEOS_TS TO user aeos;
      db2 GRANT USE OF TABLESPACE AEOS_TEMP_TS TO user aeos;
      db2 CONNECT RESET;
      "
  register: command_status
