- name: Add DB2 users
  ansible.builtin.include_role:
    name: common
    tasks_from: add-db2-user
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_db2_user: icndb
    common_password: "{{ cp4ba_universal_password }}"

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=navigator-preparing-database
# Based on https://www.ibm.com/docs/en/content-navigator/3.0.11?topic=navigator-creating-db2-database-content
- name: BAN DB
  kubernetes.core.k8s_exec:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    namespace: db2
    pod: c-db2ucluster-db2u-0
    command: >
      su - db2inst1 -s /usr/bin/bash -c "
      db2 CONNECT TO CP4BA;
      db2 CREATE REGULAR TABLESPACE ICNDB_TS PAGESIZE 32 K BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE USER TEMPORARY TABLESPACE ICNDB_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;
      db2 CREATE SYSTEM TEMPORARY TABLESPACE ICNDB_SYSTMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL CP4BA_BP_32K;

      db2 GRANT DBADM ON DATABASE TO user icndb;
      db2 GRANT USE OF TABLESPACE ICNDB_TS TO user icndb;
      db2 GRANT USE OF TABLESPACE ICNDB_TEMP_TS TO user icndb;
      db2 CONNECT RESET;
      "
  register: command_status
