pm_action: install
pm_base_dir: /tmp
pm_dir_name: pm
pm_k8s_api_key: ""
pm_k8s_host: ""
pm_operator_channel: v2.0
pm_starting_csv: ibm-automation-processmining.v1.1.1
pm_version: 1.12.0.5
pm_project_name: cp4ba
pm_storage_class_name: ""
pm_universal_password: ""
pm_db2_hostname: ""
pm_mongodb_hostname: ""
pm_ca_crt_path: ""
pm_wildcard_key_path: ""
pm_wildcard_crt_path: ""
