- name: Set path to usage.md
  ansible.builtin.set_fact:
    usage_path: "{{ generic_directory }}/usage.md"

- name: Prepare Usage md
  ansible.builtin.template:
    src: usage.md.j2
    dest: "{{ usage_path }}"
    mode: u+rwx

- name: Prepare usage Config Map
  ansible.builtin.template:
    src: usage-configmap.yaml.j2
    dest: "{{ generic_directory }}/usage-configmap.yaml"
    mode: u+rwx

- name: Add the usage config map
  kubernetes.core.k8s:
    api_key: "{{ ocp_cluster_token | default(omit) }}"
    host: "{{ ocp_api_endpoint | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ generic_directory }}/usage-configmap.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15
