# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=secrets-creating-custom-bpc-workforce-secret
# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=secrets-creating-custom-bai-secret
- name: Prepare yaml file for BAI Secret
  ansible.builtin.template:
    src: bai/bai-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/bai-secret.yaml"
    mode: u+rwx

- name: Add BAI Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/bai-secret.yaml"
