# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=authoring-creating-secrets-protect-sensitive-configuration-data
- name: Prepare yaml file for BAWAUT Secret
  ansible.builtin.template:
    src: bawaut/bawaut-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/bawaut-secret.yaml"
    mode: u+rwx

- name: Add BAWAUT Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/bawaut-secret.yaml"

- name: Add BAWAUT OSs to FNCM Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    api_version: v1
    kind: Secret
    name: ibm-fncm-secret
    namespace: "{{ cp4ba_project_name }}"
    definition: |
      data:
        {{ item }}DBUsername: {{ item | b64encode }}
        {{ item }}DBPassword: {{ cp4ba_db2_universal_password | b64encode }}
  with_items:
    - badocs
    - batos
    - bados
    # Update FNCM secret for new Case History connection.
    # Make sure FNCM secret already exists
    - ch

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.3?topic=services-optional-customizing-runtime-server-properties
# Based on https://www.ibm.com/docs/en/baw/20.x?topic=work-configuring-email-notifications
# Based on https://www.ibm.com/docs/en/baw/20.x?topic=configuration-creating-100customxml-file
- name: Prepare yaml file for BAWAUT Secret
  ansible.builtin.template:
    src: bawaut/bawaut-custom-xml-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/bawaut-custom-xml-secret.yaml"
    mode: u+rwx

- name: Add BAWAUT Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/bawaut-custom-xml-secret.yaml"
