# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=manager-configuring-external-database
- name: Prepare yaml file for ODM DB Secret
  ansible.builtin.template:
    src: odm/odm-db-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/odm-db-secret.yaml"
    mode: u+rwx

- name: Add ODM DB Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/odm-db-secret.yaml"

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=access-mapping-odm-roles-iam-groups-users
# Adds cpadmin user to all roles and cpadmins to all groups.
- name: Prepare yaml file for ODM web security Secret
  ansible.builtin.template:
    src: odm/odm-web-security-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/odm-web-security-secret.yaml"
    mode: u+rwx

- name: Add ODM web security Secret
  kubernetes.core.k8s:
    api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    host: "{{ cp4ba_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/odm-web-security-secret.yaml"
