- name: Create main CP4BA DB
  include_tasks: db/main-db.yml

- name: Add DB connections to DB2MC
  ansible.builtin.include_role:
    name: common
    tasks_from: add-db2mc-connection
  vars:
    common_k8s_api_key: "{{ cp4ba_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cp4ba_k8s_host | default(omit) }}"
    common_db2_db_name: CP4BA
    common_user: "{{ cp4ba_db2mc_admin_user }}"
    common_password: "{{ cp4ba_db2mc_universal_password }}"
    common_output_directory: "{{ cp4ba_output_directory }}"
    common_db2_hostname: "{{ cp4ba_db2_hostname }}"
  when: db2mc_enabled

- name: Manage schemas for BAN
  include_tasks: db/ban.yml

- name: Manage schemas for BAS
  include_tasks: db/bas.yml
  when: cp4ba_config.optional_components.bas

- name: Manage schemas for ODM
  include_tasks: db/odm.yml
  when: cp4ba_config.deployment_patterns.decisions

- name: Manage schemas for FNCM
  include_tasks: db/fncm.yml
  when: cp4ba_config.deployment_patterns.content

- name: Manage schemas for IER
  include_tasks: db/ier.yml
  when: cp4ba_config.optional_components.ier

- name: Manage schemas for AAE
  include_tasks: db/aae.yml
  when: cp4ba_config.deployment_patterns.application

- name: Manage schemas for AAE Data persistence
  include_tasks: db/aae-data-persistence.yml
  when: cp4ba_config.optional_components.ae_data_persistence

- name: Manage schemas for ADP
  include_tasks: db/adp.yml
  when: cp4ba_config.deployment_patterns.document_processing

- name: Manage schemas for BAWAUT
  include_tasks: db/bawaut.yml
  when: cp4ba_config.deployment_patterns.workflow and cp4ba_config.optional_components.baw_authoring
