- name: Load internal variables
  ansible.builtin.include_vars: internal-variables.yml

- name: Set ldap configuration TDS
  ansible.builtin.set_fact:
    lc_tds_user_filter: "{{ lc_tds_user_filter  | default('(&('+lc_ldap_user_id_attribute+'=%v)(objectclass='+lc_ldap_user_object_class+'))') }}"
    lc_tds_group_filter: "{{ lc_tds_group_filter  | default('(&('+lc_ldap_group_id_attribute+'=%v)(|(objectclass='+lc_ldap_group_object_class+')(objectclass=groupofuniquenames)(objectclass=groupofurls)))') }}"
  when: ('IBM Security Directory Server' in lc_selected_ldap_type)

- name: Set ldap configuration AD
  ansible.builtin.set_fact:
    lc_ad_user_filter: "{{ lc_ad_user_filter | default('(&('+lc_ldap_user_id_attribute+'=%v)(objectcategory='+lc_ldap_user_object_class+'))') }}"
    lc_ad_group_filter: "{{ lc_ad_group_filter | default('(&('+lc_ldap_group_id_attribute+'=%v)(objectcategory='+lc_ldap_group_object_class+'))') }}"
  when: ('Microsoft Active Directory' in lc_selected_ldap_type)

- name: CP4BA config variables
  ansible.builtin.set_fact:
    cp4ba_config:
      deployment_patterns:
        foundation: true
        decisions: true
        decisions_ads: true
        content: true
        application: true
        document_processing: true
        workflow: true
        workflow_workstreams: false
      optional_components:
        bas: true
        bai: true
        decision_center: true
        decision_runner: true
        decision_server_runtime: true
        ads_designer: true
        ads_runtime: true
        cmis: true
        # css: Content Search Services
        css: true
        # es = External Share
        es: true
        # tm = Task Management
        tm: true
        # ier = IBM Enterprise Records
        ier: true
        app_designer: true
        ae_data_persistence: true
        document_processing_designer: true
        document_processing_runtime: false
        baw_authoring: true
        application: true
  when: cp4ba_config is not defined

- name: Openldap config variable
  ansible.builtin.set_fact:
    openldap_enabled: true'
  when: openldap_enabled is not defined

- name: Mongodb config variable
  ansible.builtin.set_fact:
    mongodb_enabled: true
  when: mongodb_enabled is not defined

- name: Kibana config variable
  ansible.builtin.set_fact:
    kibana_enabled: true
  when: kibana_enabled is not defined

- name: Mail config variable
  ansible.builtin.set_fact:
    mail_enabled: true
  when: mail_enabled is not defined

- name: Gitea config variable
  ansible.builtin.set_fact:
    gitea_enabled: true
  when: gitea_enabled is not defined

- name: Config External LDAP
  include_tasks: external-ldap.yml
  when: lc_custom_config_secret | length > 0